name: Update Football Data

on:
  schedule:
    - cron: '0 6 * * 1'  # lunes 6 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Crear credenciales
        run: echo '${{ secrets.GOOGLE_CREDS }}' > creds.json

      - name: Ejecutar script
        run: python football_script.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
